<a href="https://colab.research.google.com/github/jachmehoff8997/dllab/blob/main/DLlab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Learning rules

In [3]:
# Import necessary libraries
import cv2
import tensorflow as tf
import tensorflow_hub as hub
import matplotlib.pyplot as plt
import numpy as np
!curl https://imgur.com/9ooB60I.jpeg -o style.jpeg
!curl https://i.imgur.com/F28w3Ac.jpg -o content.jpg

# Load the images
def load_img(path):
    img = cv2.imread(path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img / 255.0
    return img

# Load content and style images
content_image = load_img('content.jpg')
style_image = load_img('style.jpeg')

# Load the TensorFlow Hub model
model = hub.load('https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2')

# Apply the style transfer
def apply_style(content_image, style_image):
    content_image = content_image[np.newaxis, ...].astype('float32')
    content_image = tf.convert_to_tensor(content_image)

    style_image = cv2.resize(style_image, (256, 256))
    style_image = style_image[np.newaxis, ...].astype('float32')
    style_image = tf.convert_to_tensor(style_image)

    outputs = model(tf.constant(content_image), tf.constant(style_image))
    stylized_image = outputs[0]
    return stylized_image

# Display the stylized image
stylized_img = apply_style(content_image, style_image)
plt.xticks([])
plt.yticks([])
plt.grid(False)
plt.imshow(stylized_img[0])
plt.show()

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  100k  100  100k    0     0  1044k      0 --:--:-- --:--:-- --:--:-- 1053k


error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


3.Perceptrons

In [5]:
import numpy as np

class Perceptron:
    """
    A simple perceptron classifier.
    """
    def __init__(self, weights=None, bias=0):
        self.weights = weights
        self.bias = bias

    def initialize(self, n_features):
        """
        Set initial weights and bias to zeros if not provided.
        """
        if self.weights is None:
            self.weights = np.zeros(n_features)
        if self.bias is None:
            self.bias = 0

    def predict(self, inputs):
        """
        Predict the class labels for new input data.
        Calculate the step activation function.
        """
        activation = np.dot(inputs, self.weights) + self.bias
        return 1 if activation > 0 else 0

    def train(self, X, y, epochs=100, learning_rate=0.1):
        """
        Train the perceptron using the input data and target labels.
        """
        # Initialize the weights and bias
        self.initialize(X.shape[1])

        for epoch in range(epochs):
            for inputs, label in zip(X, y):
                # Get prediction
                y_pred = self.predict(inputs)
                # Calculate delta error
                error = label - y_pred
                # Update weights and bias
                self.weights += learning_rate * error * inputs
                self.bias += learning_rate * error

# Example usage with customized weights
X_train = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
y_train = np.array([0, 0, 0, 1])
custom_weights = np.array([0.2, 0.4, 0.6])  # Customized weights
custom_bias = -0.5  # Customized bias

# Create Perceptron object with custom weights and bias
p = Perceptron(weights=custom_weights, bias=custom_bias)

# Train the perceptron
p.train(X_train, y_train, epochs=100, learning_rate=0.1)

# Test prediction
test_input = np.array([0, 1, 1])
print("Prediction:", p.predict(test_input))  # Output: 0

# Evaluate accuracy
X_test = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
y_test = np.array([0, 0, 0, 1])

# Predict on test data
pred = np.array([p.predict(x) for x in X_test])

# Calculate accuracy
accuracy = np.mean(pred == y_test) * 100
print("Accuracy:", accuracy)

Prediction: 0
Accuracy: 100.0


5.image restyling

In [6]:
import numpy as np

# Hebbian Learning Rule
def hebbian_learning_rule(input_pattern, weight_matrix):
    return weight_matrix + np.outer(input_pattern, input_pattern)

# Perceptron Learning Rule
def perceptron_learning_rule(input_pattern, target, weight_vector, learning_rate):
    prediction = np.dot(weight_vector, input_pattern)
    error = target - prediction
    return weight_vector + learning_rate * error * input_pattern

# Delta Learning Rule
def delta_learning_rule(input_pattern, target, weight_matrix, learning_rate):
    prediction = np.dot(weight_matrix, input_pattern)
    error = target - prediction
    return weight_matrix + learning_rate * np.outer(error, input_pattern)

# Correlation Learning Rule
def correlation_learning_rule(input_pattern, weight_matrix):
    return weight_matrix + np.outer(input_pattern, input_pattern)

# Out Star Learning Rule
def out_star_learning_rule(input_pattern, weight_matrix, learning_rate):
    return weight_matrix + learning_rate * np.outer(input_pattern, input_pattern)

input_size = 3

# Initialize weights with random values
hebbian_weights = np.random.rand(input_size, input_size)
perceptron_weights = np.random.rand(input_size)
delta_weights = np.random.rand(input_size, input_size)
correlation_weights = np.random.rand(input_size, input_size)
out_star_weights = np.random.rand(input_size, input_size)

# Example input pattern and target
input_pattern = np.array([1, -1, 0])
target = np.array([1, 0, -1])
learning_rate = 0.1

# Update weights using different learning rules
hebbian_weights = hebbian_learning_rule(input_pattern, hebbian_weights)
perceptron_weights = perceptron_learning_rule(input_pattern, target[0], perceptron_weights, learning_rate)
delta_weights = delta_learning_rule(input_pattern, target, delta_weights, learning_rate)
correlation_weights = correlation_learning_rule(input_pattern, correlation_weights)
out_star_weights = out_star_learning_rule(input_pattern, out_star_weights, learning_rate)

# Print updated weights
print("Updated Hebbian Weights:\n", hebbian_weights)
print("\nUpdated Perceptron Weights:\n", perceptron_weights)
print("\nUpdated Delta Weights:\n", delta_weights)
print("\nUpdated Correlation Weights:\n", correlation_weights)
print("\nUpdated Out Star Weights:\n", out_star_weights)

Updated Hebbian Weights:
 [[ 1.19604042 -0.40891704  0.51688801]
 [-0.80500576  1.11132618  0.42139586]
 [ 0.34666524  0.71196842  0.88225788]]

Updated Perceptron Weights:
 [0.88956885 0.09648911 0.78743353]

Updated Delta Weights:
 [[0.61692365 0.13341881 0.43267892]
 [0.78775214 0.68036325 0.23208412]
 [0.88048664 1.00475197 0.76343771]]

Updated Correlation Weights:
 [[ 1.7201964  -0.5015583   0.42116667]
 [-0.9051306   1.11596023  0.20666706]
 [ 0.33574168  0.49753173  0.25789678]]

Updated Out Star Weights:
 [[0.55186485 0.32337899 0.89419064]
 [0.52832023 0.80941757 0.30239167]
 [0.98289565 0.26689553 0.12987891]]
